export const positions = `
CREATE TABLE positions (id int, company_name char, country char, city char, position char, salary int);

INSERT INTO positions VALUES (1, 'LinkedIn', 'United States', 'San Francisco', 'ML Engineer', 140000);
INSERT INTO positions VALUES (2, 'LinkedIn', 'United States', 'New York' ,'ML Engineer', 100000);
INSERT INTO positions VALUES (3, 'LinkedIn', 'United States', 'Sunnyvale' ,'Data Engineer', 110000);
INSERT INTO positions VALUES (4, 'Meta', 'United States', 'New York' , 'Data Analyst', 130000);
INSERT INTO positions VALUES (5, 'Meta', 'United States', 'San Francisco' ,'Data Engineer', 130000);
INSERT INTO positions VALUES (6, 'Meta', 'United Kingdom', 'London' ,'Data Engineer', 130000);
INSERT INTO positions VALUES (7, 'ING', 'Netherlands', 'Amsterdam' ,'Data Engineer', 80000);
INSERT INTO positions VALUES (8, 'ING', 'Netherlands', 'Amsterdam' ,'Data Analyst', 80000);
INSERT INTO positions VALUES (9, 'ING', 'Netherlands', 'Amsterdam' ,'Data Scientist', 82000);
INSERT INTO positions VALUES (10, 'KPMG', 'Netherlands', 'Amsterdam' ,'Data Engineer', 87000);
INSERT INTO positions VALUES (11, 'KPMG', 'Netherlands', 'Rotterdam' ,'Data Analyst', 80000);
INSERT INTO positions VALUES (12, 'KPMG', 'Netherlands', 'Amsterdam' ,'Data Scientist', 80000);
INSERT INTO positions VALUES (13, 'PwC', 'Netherlands', 'Amsterdam' ,'Data Engineer', 83000);
INSERT INTO positions VALUES (14, 'PwC', 'Netherlands', 'Amsterdam' ,'Data Analyst', 80000);
INSERT INTO positions VALUES (15, 'Deloitte', 'Netherlands', 'Amsterdam' ,'Data Engineer', 95000);
INSERT INTO positions VALUES (16, 'Deloitte', 'Netherlands', 'Amsterdam' ,'AI Consultant', 90000);
INSERT INTO positions VALUES (17, 'Deloitte', 'Netherlands', 'Amsterdam' ,'Data Scientist', 95000);
INSERT INTO positions VALUES (18, 'EY', 'Netherlands', 'Amsterdam' ,'Data Engineer', 85000);
INSERT INTO positions VALUES (19, 'EY', 'Netherlands', 'Rotterdam' ,'Data Scientist', 84000);
INSERT INTO positions VALUES (20, 'TikTok', 'United States', 'Los Angeles' ,'Data Engineer', 125000);
INSERT INTO positions VALUES (21, 'TikTok', 'United States', 'New York' ,'ML Engineer', 120000);
INSERT INTO positions VALUES (22, 'TikTok', 'United States', 'Los Angeles' ,'Data Scientist', 122000);
INSERT INTO positions VALUES (23, 'Twitter', 'United States', 'San Francisco' ,'Data Engineer', 130000);
INSERT INTO positions VALUES (24, 'Twitter', 'United States', 'New York' ,'Data Analyst', 120000);
INSERT INTO positions VALUES (25, 'Twitter', 'United States', 'San Francisco' ,'Data Scientist', 125000);
INSERT INTO positions VALUES (26, 'Google', 'United States', 'Mountain View' ,'Data Engineer', 140000);
INSERT INTO positions VALUES (27, 'Google', 'United States', 'New York' ,'Data Analyst', 130000);
INSERT INTO positions VALUES (28, 'Google', 'United States', 'Mountain View' ,'Data Scientist', 135000);
INSERT INTO positions VALUES (29, 'Apple', 'United States', 'Cupertino' ,'Data Engineer', 145000);
INSERT INTO positions VALUES (30, 'Apple', 'United States', 'New York' ,'Data Analyst', 135000);
INSERT INTO positions VALUES (31, 'Apple', 'United States', 'Cupertino' ,'Data Scientist', 140000);
INSERT INTO positions VALUES (32, 'Microsoft', 'United States', 'Redmond' ,'Data Engineer', 150000);
INSERT INTO positions VALUES (33, 'Microsoft', 'United States', 'New York' ,'Data Analyst', 140000);
INSERT INTO positions VALUES (34, 'Microsoft', 'United States', 'Redmond' ,'Data Scientist', 145000);
INSERT INTO positions VALUES (35, 'Rabobank', 'Netherlands', 'Utrecht' ,'Data Engineer', 80000);
INSERT INTO positions VALUES (36, 'Rabobank', 'Netherlands', 'Amsterdam' ,'Data Analyst', 80000);
`